---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: public-gateway
  namespace: emissary
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      additionalPort: 8080
      action: Redirect
  tlsSecret:
    name: emissary-gateway-tls
  previewUrl: false
