---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-https
  namespace: emissary
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
  tls:
    secret: emissary-gateway-tls
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-http
  namespace: emissary
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
